using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum EffectType
{
    None = 0,
    LevelUp = 1,
    GoldSpend = 2,
    UnlockCharacter = 3,
    DeathExplosion = 4,
    DyingExplosion = 36,
    HitExplosion = 5,
    DefeatExplosion = 6,
    VictoryExplosion = 7,
    CommonExplo = 8,
    RareExplo = 9,
    EpicExplo = 10,
    LegendaryExplo = 11,
    CommonGlow = 12,
    RareGlow = 13,
    EpicGlow = 14,
    LegendaryGlow = 15,
    CommonEquip = 16,
    RareEquip = 17,
    EpicEquip = 18,
    LegendaryEquip = 19,
    MageGust = 29,
    MageProjectile = 20,
    MageExplo = 21,
    KnightExplo = 22,
    KnightGust = 34,
    RangerExplo = 23,
    RangerGust = 35,
    ShamanGust = 30,
    ShamanExplo = 24,
    ShamanProjectile = 25,
    AssassinExplo = 26,
    AssassinGust = 31,
    WarriorGust = 32,
    WarriorExplo = 27,
    BruteGust = 33,
    BruteExplo = 28,
    DyingMonster = 37,
    DeathMonster = 38,
    BruteDeath = 39,
    RatBossGust = 40,
    RatBossProjectile = 41,
    RatBossExplo = 42,
    RatSoldierProjectile = 43,
    RatSoldierExplo = 44,
    RatSoldierGust = 45,
    DemonExplo = 46,
    DemonBossExplo = 47,
    DemonProjectile = 48,
    DemonGust = 49,
    DemonBossGust = 50,
    ReaperGust = 51,
    ReaperExplo = 52,
    ReaperBossGust = 53,
    ReaperBossExplo = 54,
    CommonUIGlow = 55,
    RareUIGlow = 56,
    EpicUIGlow = 57,
    LegendaryUIGlow = 58,
    BossGust = 59,
    BossExplo = 60,
    BossAttack = 61,
    BossDeath = 62,
    RatBossDeath = 63,
    InjuredEffect = 64,
    DestroyedItem = 65,
    DemonBossDeath = 66,
    DemonDeath = 67,
    ReaperDeath = 68,
    ReaperBossDeath = 69,
    StrengthPotionExplo = 70,
    StaminaPotionExplo = 71,
    LuckPotionExplo = 72,
    StrengthPotionEffect = 73,
    StaminaPotionEffect = 74,
    LuckPotionEffect = 75,
}
[CreateAssetMenu(fileName = "New Effect", menuName = "Scriptable/Effect")]

public class ScriptableEffect : ScriptableObject
{
    public GameObject effectPrefab;
    public EffectType effectType;
}
